<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/media" class="active">Media List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                Media List
                <a href="/admin/media/upload" class="btn btn-sm"><i class="icon-upload align-top bigger-125"></i> Upload Media</a>
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> Items
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline">
                            <div class="form-group">
                                <?=$form->render('q', array(
                                    'placeholder' => 'Keyword',
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('status', array(
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('uid', array())?>
                                <?=$form->render('username', array(
                                    'placeholder' => 'Username',
                                    'class' => 'form-control input-sm autocomplete',
                                    'data-autocomplete-source' => '/admin/user/process/suggestions?query=%QUERY',
                                    'data-autocomplete-target' => 'input[name=uid]',
                                    'data-autocomplete-fill-name' => 'id',
                                    'data-autocomplete-display-key' => 'username',
                                ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('extension', array(
                                    'class' => 'form-control input-sm',
                                    'placeholder' => 'File Extension',
                                ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('image', array(
                                ))?>
                            </div>
                           <span>
                                <label for="filter-from-limit">Display</label> 
                            </span>
                            <div class="form-group">
                                <?=$form->render('per_page', array(
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <button class="btn btn-info btn-sm form-control" type="submit">
                                <i class="icon-search bigger-110"></i>
                                Filter 
                            </button>
                        </form>

                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable   table-sortable" id="post-grid"  data-sortable-key="order" data-sortable-default="-created_at">
                    <thead>
                        <tr>
                            <th class="center">
                                <label>
                                    <input type="checkbox" class="ace">
                                    <span class="lbl"></span>
                                </label>
                            </th>
                            <th class="hidden-480">
                                <a href="<?=$this->tag->uri('/admin/media', $pager->query)?>" class="sortable-link" data-sortable-value="id">ID</a>
                            </th>
                            <th>Filename</th>
                            <th class="hidden-480">File Size</th>
                            <th>User</th>
                            <th>
                                <a href="<?=$this->tag->uri('/admin/media', $pager->query)?>" class="sortable-link" data-sortable-value="created_at" data-sortable-default="-created_at">
                                    <i class="icon-time bigger-110"></i>
                                    Upload Time
                                </a>
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        <?foreach($pager->items as $item):?>
                        <tr>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" value="<?=$item->id?>"  data-batch-source="<?=$item->id?>">
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td class="hidden-480"><?=$item->id?></td>
                            <td>
                                <?if($item->isImage):?>
                                <a href="<?=$item->getFullUrl()?>"><img src="<?=$this->tag->thumb($item->getLocalUrl(), 'c_fill,h_30,w_40')?>" /></a>
                                <?endif?>
                                <a href="/admin/media/edit/<?=$item->id?>"><?=$item->originalName?></a>
                            </td>
                            <td><?=$item->getReadableFileSize()?></td>
                            <td><?=$item->User ? $item->User->username : ''?></td>
                            <td><?=$this->tag->datetime($item->createdAt)?></td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?=$item->getFullUrl()?>"  class="btn btn-xs btn-info" target="_blank">
                                        <i class="icon-zoom-in bigger-120"></i>
                                    </a>
                                    <button class="btn btn-xs btn-danger ajax-form-sumbit" data-ajax-form="1" date-method="delete" data-form-action="/admin/media/delete/<?=$item->id?>" data-confirm="1" data-confirm-message="<?=sprintf('Item %s will be deleted, are you sure?', $item->title)?>" data-callback="form.closest('tr').hide();">
                                        <i class="icon-trash bigger-120"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                        <!--
                        <div class="btn-group">
                            <button class="btn btn-xs btn-success ajax-form-sumbit" data-batch-form="1" data-source-name="id" data-source-selectors="#post-grid input[data-batch-source]" date-method="put" data-form-action="/admin/post/batch" data-callback="window.location.reload();">
                                <input type="hidden" data-name="status" value="published" >
                                <i class="icon-ok bigger-120"></i>
                            </button>

                            <button class="btn btn-xs btn-warning ajax-form-sumbit" data-batch-form="1" data-source-name="id" data-source-selectors="#post-grid input[data-batch-source]" date-method="put" data-form-action="/admin/post/batch" data-callback="window.location.reload();">
                                <input type="hidden" data-name="status" value="deleted" >
                                <i class="icon-eye-close bigger-120"></i>
                            </button>
                        </div>
                        -->
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/media',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
