<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashborad">Home</a>
        </li>

        <li>
        <a href="/admin/media">Media</a>
        </li>
        <li class="active">File Upload</li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">
    <div class="page-header">
        <h1>
            Upload Files
            <small>
                <i class="icon-double-angle-right"></i>
                Drag &amp; drop file upload with image preview
            </small>
        </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <div id="dropzone">
                <form action="/admin/upload" class="dropzone" method="POST" enctype="multipart/form-data">
                    <div class="fallback">
                        <input name="file" type="file" multiple="" />
                        <input type="submit" />
                    </div>
                </form>
            </div><!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
